# This is a basic workflow to help you get started with Actions

name: Start CI

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/1 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Start server
        run: |
          pip3 install setuptools
          unzip webpy
          cd webpy/
          python setup.py install
          cd root/
          python main.py
